[project]
name = "Indexation-Lab"
version = "0.1.0"
description = "Lab Indexation corpus + inverted index + Elasticsearch"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "nltk>=3.9.2",
    "tqdm>=4.67.1",
]
